#!/usr/bin/env bash
# 4DGaussians — https://github.com/hustvl/4DGaussians
# Prerequisite: /workspace = cloned repo root (bind-mounted by docker_agent)
# Generated by: rocm-install-script-generator skill v1.1.0
#
# ⚠  CUDA COMPATIBILITY WARNING:
#    README targets python=3.7, pytorch=1.13.1+cu116.
#    The submodule `depth-diff-gaussian-rasterization` contains CUDA kernels
#    that may not compile on ROCm without patches.
#    This script uses python=3.10 and ROCm PyTorch; kernel compilation is attempted
#    but may require manual fixes.
set -e
cd /workspace

# ── Block A: git submodule init ───────────────────────────────────────────────
git config --global --add safe.directory /workspace
git submodule update --init --recursive

# ── Block B: Conda env ────────────────────────────────────────────────────────
# README says python=3.7 but support has dropped; use 3.10 for ROCm compatibility
conda create -n gaussians4d python=3.10 -y
source /opt/conda/etc/profile.d/conda.sh && conda activate gaussians4d

# ── Block C: ROCm PyTorch ─────────────────────────────────────────────────────
pip uninstall -y torch torchvision torchaudio
pip3 install --pre torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 \
  --index-url https://download.pytorch.org/whl/rocm6.4

# ── Block E: requirements.txt ─────────────────────────────────────────────────
if [ -f requirements.txt ]; then
  EXCLUDE_PKGS="torch|torchvision|torchaudio"
  grep -vEi "^(${EXCLUDE_PKGS})([<>=!~;[:space:]]|$)" requirements.txt \
    > requirements.tmp && mv requirements.tmp requirements.tmp2
  pip install -r requirements.tmp2
  rm -f requirements.tmp2
fi

# ── Block G: CUDA/ROCm submodule extensions ───────────────────────────────────
export PYTORCH_ROCM_ARCH="gfx906;gfx908;gfx90a;gfx1030;gfx1100"

# depth-diff-gaussian-rasterization — core render extension; may need ROCm patches
echo "[INFO] Building depth-diff-gaussian-rasterization ..."
pip install -e submodules/depth-diff-gaussian-rasterization --no-build-isolation || \
  echo "[WARN] depth-diff-gaussian-rasterization build failed — ROCm patches likely needed"

# simple-knn
echo "[INFO] Building simple-knn ..."
pip install -e submodules/simple-knn --no-build-isolation || \
  echo "[WARN] simple-knn build failed"

# ── Block H: Smoke test ───────────────────────────────────────────────────────
python -c "import torch; print('torch', torch.__version__, '| cuda:', torch.cuda.is_available())"
python -c "from diff_gaussian_rasterization import GaussianRasterizationSettings; print('rasterization OK')" || \
  echo "[WARN] diff_gaussian_rasterization not importable — check build log above"
python -c "from simple_knn._C import distCUDA2; print('simple_knn OK')" || \
  echo "[WARN] simple_knn not importable — check build log above"
