#!/usr/bin/env bash
# Any4D — https://github.com/Any-4D/Any4D
# Prerequisite: /workspace = cloned repo root (bind-mounted by docker_agent)
# Generated by: rocm-install-script-generator skill v1.1.0
# Note: pyproject.toml has optional deps [all], [gradio]. Install core only.
set -e
cd /workspace

# ── Block B: Conda env ────────────────────────────────────────────────────────
# README uses python=3.12 via conda
conda create -n any4d python=3.12 -y
source /opt/conda/etc/profile.d/conda.sh && conda activate any4d

# ── Block C: ROCm PyTorch ─────────────────────────────────────────────────────
# README says "Note that we don't pin a specific version of PyTorch."
pip uninstall -y torch torchvision torchaudio
pip install --pre torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 \
  --index-url https://download.pytorch.org/whl/rocm6.4

# ── Block E: Strip torch pins from pyproject.toml ────────────────────────────
# pyproject.toml pins "torch~=2.6.0" (==2.6.x range) which conflicts with
# the ROCm 2.8.0 wheel installed above. Remove torch/torchvision/torchaudio
# lines before the editable install so pip does not try to downgrade torch.
python3 -c "
import re, pathlib; p = pathlib.Path('pyproject.toml')
pat = re.compile(r'[ \t]*\"(torch|torchvision|torchaudio|xformers|gsplat|flash.attn|triton|torch.geometric|pyg.lib|torch.scatter|torch.sparse|torch.cluster|torch.spline.conv)[^\"]*\",?[^\n]*\n', re.I)
txt = pat.sub('', p.read_text()); p.write_text(txt)
print('pyproject.toml: Block C/D package pins removed')
"

# ── Block F: pyproject.toml — core-only install ───────────────────────────────
# Do NOT use pip install -e ".[all]" — optional deps are untested on ROCm
# and may pull in conflicting packages (rerun-sdk, gradio, etc.)
pip install -e .

# ── Block H: Smoke test ───────────────────────────────────────────────────────
python -c "import torch; print('torch', torch.__version__, '| cuda:', torch.cuda.is_available())"
python -c "import any4d; print('any4d import OK')" || \
  python -c "import sys; sys.path.insert(0, '.'); print('any4d install check: workspace accessible')"
