#!/usr/bin/env bash
# Anything-3D — https://github.com/Anything-of-anything/Anything-3D
# Prerequisite: /workspace = cloned repo root (bind-mounted by docker_agent)
# Generated by: rocm-install-script-generator skill v1.1.0
#
# ⚠  COLLECTION REPO WARNING:
#    Anything-3D is a multi-module collection (AnyObject3D, AnyNeRF, AnyFace3D,
#    novel-view). There is NO unified root-level requirements.txt or setup.py.
#    This script sets up the core shared dependencies (SAM + Zero-1-to-3) used
#    across sub-projects, then installs AnyObject3D as the primary entry point.
#    Each sub-project may need additional package-specific setup.
set -e
cd /workspace

# ── Block B: Conda env ────────────────────────────────────────────────────────
conda create -n anything3d python=3.10 -y
source /opt/conda/etc/profile.d/conda.sh && conda activate anything3d

# ── Block C: ROCm PyTorch ─────────────────────────────────────────────────────
pip uninstall -y torch torchvision torchaudio
pip3 install --pre torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 \
  --index-url https://download.pytorch.org/whl/rocm6.4

# ── Block E: Core shared dependencies ────────────────────────────────────────
# Segment Anything (SAM) — used by all sub-projects
pip install git+https://github.com/facebookresearch/segment-anything.git

# Sub-project specific requirements (install whichever subdir is relevant)
for subdir in AnyObject3D AnyNeRF AnyFace3D novel-view; do
  if [ -f "${subdir}/requirements.txt" ]; then
    echo "[INFO] Installing requirements for ${subdir} ..."
    EXCLUDE_PKGS="torch|torchvision|torchaudio"
    grep -vEi "^(${EXCLUDE_PKGS})([<>=!~;[:space:]]|$)" "${subdir}/requirements.txt" \
      > "${subdir}/requirements.tmp"
    pip install -r "${subdir}/requirements.tmp"
    rm -f "${subdir}/requirements.tmp"
  fi
done

# ── Block H: Smoke test ───────────────────────────────────────────────────────
python -c "import torch; print('torch', torch.__version__, '| cuda:', torch.cuda.is_available())"
python -c "import segment_anything; print('segment_anything (SAM) OK')"
echo "[INFO] Collection repo — verify individual sub-projects as needed"
