#!/usr/bin/env bash
# DimensionX — https://github.com/wenqsun/DimensionX
# Prerequisite: /workspace = cloned repo root (bind-mounted by docker_agent)
# Generated by: rocm-install-script-generator skill v1.1.0
# Note: DimensionX has two separate environments:
#   1. cogvideo  — controllable video generation (THIS SCRIPT)
#   2. instantsplat — 3D scene optimization (submodule, needs separate setup)
# This script covers the main cogvideo component only.
set -e
cd /workspace

# ── Block A: git submodule init ───────────────────────────────────────────────
git config --global --add safe.directory /workspace
# Init only the cogvideo submodule; instantsplat requires its own env
git submodule update --init cogvideo 2>/dev/null || git submodule update --init --recursive

# ── Block B: Conda env ────────────────────────────────────────────────────────
# README specifies python=3.10
conda create -n dimensionx python=3.10 -y
source /opt/conda/etc/profile.d/conda.sh && conda activate dimensionx

# ── Block C: ROCm PyTorch ─────────────────────────────────────────────────────
# README uses pytorch-cuda=12.1; override with ROCm 6.4
pip uninstall -y torch torchvision torchaudio
pip3 install --pre torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 \
  --index-url https://download.pytorch.org/whl/rocm6.4

# ── Block E: cogvideo/requirements.txt ────────────────────────────────────────
# Main requirements live under cogvideo/ subdirectory
if [ -f cogvideo/requirements.txt ]; then
  EXCLUDE_PKGS="torch|torchvision|torchaudio"
  grep -vEi "^(${EXCLUDE_PKGS})([<>=!~;[:space:]]|$)" cogvideo/requirements.txt \
    > cogvideo/requirements.tmp && mv cogvideo/requirements.tmp cogvideo/requirements.tmp2
  pip install -r cogvideo/requirements.tmp2
  rm -f cogvideo/requirements.tmp2
else
  echo "[WARN] cogvideo/requirements.txt not found — skipping bulk install"
fi

# ── Block H: Smoke test ───────────────────────────────────────────────────────
python -c "import torch; print('torch', torch.__version__, '| cuda:', torch.cuda.is_available())"
python -c "import diffusers, transformers; print('diffusers & transformers OK')" || \
  echo "[WARN] diffusers/transformers not importable — check cogvideo/requirements.txt"
