#!/usr/bin/env bash
# FLARE — https://github.com/ant-research/FLARE
# Prerequisite: /workspace = cloned repo root (bind-mounted by docker_agent)
# Generated by: rocm-install-script-generator skill v1.1.0
# Note: README uses conda pytorch-cuda=12.1; overridden with ROCm 6.4 wheels.
#       FLARE embeds dust3r and mast3r as submodules; git submodule init required.
set -e
cd /workspace

# ── Block A: git submodule init ───────────────────────────────────────────────
git config --global --add safe.directory /workspace
git submodule update --init --recursive

# ── Block B: Conda env ────────────────────────────────────────────────────────
# README says python=3.8; use 3.12 to match base image + pytorch3d pre-built wheel (cp312).
conda create -n flare python=3.12 -y
source /opt/conda/etc/profile.d/conda.sh && conda activate flare

# ── Block C: ROCm PyTorch ─────────────────────────────────────────────────────
pip uninstall -y torch torchvision torchaudio
pip install --pre torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 \
  --index-url https://download.pytorch.org/whl/rocm6.4

# ── Block D: gsplat via AMD ROCm index ────────────────────────────────────────
# Source build requires CUDA toolchain and will fail on ROCm; use AMD PyPI index.
pip install gsplat \
  --index-url=https://pypi.amd.com/simple \
  --extra-index-url https://pypi.org/simple

# ── Block D+: pytorch3d — pre-built ROCm 6.4 / Python 3.12 wheel ─────────────
# Use ZJLi2013 fork pre-built wheel; no source build or --no-build-isolation needed.
pip install https://github.com/ZJLi2013/pytorch3d/releases/download/rocm6.4-py3.12/pytorch3d-0.7.9-cp312-cp312-linux_x86_64.whl

# ── Block E: requirements.txt ─────────────────────────────────────────────────
# Exclude all Block C/D packages + pytorch3d (handled above)
EXCLUDE_PKGS="torch|torchvision|torchaudio|xformers|gsplat|flash.attn|triton|torch.geometric|pyg.lib|torch.scatter|torch.sparse|torch.cluster|torch.spline.conv|pytorch3d"
# Pass 1: strip package-name form
grep -vEi "^(${EXCLUDE_PKGS})([<>=!~;[:space:]]|$)" requirements.txt \
  > requirements.tmp && mv requirements.tmp requirements.txt
# Pass 2: strip git+URL form (gsplat, pytorch3d both appear as VCS URLs in this repo)
grep -vEi "git\+https?://[^[:space:]]*(gsplat|pytorch3d)" requirements.txt \
  > requirements.tmp && mv requirements.tmp requirements.txt
pip install -r requirements.txt

# README also does: conda uninstall ffmpeg && conda install -c conda-forge ffmpeg
conda install -c conda-forge ffmpeg -y

# ── Block H: Smoke test ───────────────────────────────────────────────────────
python -c "import torch; print('torch', torch.__version__, '| cuda:', torch.cuda.is_available())"
python -c "import gsplat; print('gsplat OK')" || echo "[WARN] gsplat not importable — check AMD index availability for your ROCm version"
