#!/usr/bin/env bash
# GEN3C — https://github.com/nv-tlabs/GEN3C
# Prerequisite: /workspace = cloned repo root (bind-mounted by docker_agent)
# Generated by: rocm-install-script-generator skill v1.1.0
#
# ⚠  CUDA COMPATIBILITY WARNING:
#    GEN3C is built on NVIDIA Cosmos and uses CUDA_HOME=$CONDA_PREFIX throughout.
#    ROCm compatibility is NOT guaranteed. This script attempts a best-effort install.
#    Inference commands reference CUDA_HOME; on ROCm set: ROCM_HOME=$CONDA_PREFIX
set -e
cd /workspace

# ── Block A: git submodule init ───────────────────────────────────────────────
git config --global --add safe.directory /workspace
git submodule update --init --recursive

# ── Block B: Conda env ────────────────────────────────────────────────────────
conda create -n gen3c python=3.10 -y
source /opt/conda/etc/profile.d/conda.sh && conda activate gen3c

# ── Block C: ROCm PyTorch ─────────────────────────────────────────────────────
pip uninstall -y torch torchvision torchaudio
pip3 install --pre torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 \
  --index-url https://download.pytorch.org/whl/rocm6.4

# ── Block E: requirements.txt ─────────────────────────────────────────────────
if [ -f requirements.txt ]; then
  EXCLUDE_PKGS="torch|torchvision|torchaudio"
  grep -vEi "^(${EXCLUDE_PKGS})([<>=!~;[:space:]]|$)" requirements.txt \
    > requirements.tmp && mv requirements.tmp requirements.tmp2
  pip install -r requirements.tmp2
  rm -f requirements.tmp2
fi

# GEN3C is packaged under cosmos_predict1 — install as editable
pip install -e . --no-build-isolation || true

# ── Block H: Smoke test ───────────────────────────────────────────────────────
python -c "import torch; print('torch', torch.__version__, '| cuda:', torch.cuda.is_available())"
python -c "import cosmos_predict1; print('cosmos_predict1 OK')" || \
  python -c "import sys; sys.path.insert(0, '.'); import cosmos_predict1; print('cosmos_predict1 OK (sys.path)')" || \
  echo "[WARN] cosmos_predict1 not importable — GEN3C may require manual CUDA build"
