#!/usr/bin/env bash
# mvinverse — https://github.com/Maddog241/mvinverse
# Prerequisite: /workspace = cloned repo root (bind-mounted by docker_agent)
# Generated by: rocm-install-script-generator skill v1.1.0
# Note: README pins torch==2.5.1+cu118; overridden here with ROCm 6.4 wheels.
set -e
cd /workspace

# ── Block B: Conda env ────────────────────────────────────────────────────────
conda create -n mvinverse python=3.12 -y
source /opt/conda/etc/profile.d/conda.sh && conda activate mvinverse

# ── Block C: ROCm PyTorch ─────────────────────────────────────────────────────
pip uninstall -y torch torchvision torchaudio
pip3 install --pre torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 \
  --index-url https://download.pytorch.org/whl/rocm6.4

# ── Block E: Filter requirements.txt + bulk install ───────────────────────────
# README additionally installs opencv-python and huggingface_hub==0.35.0;
# requirements.txt likely covers these. Torch family excluded to prevent override.
EXCLUDE_PKGS="torch|torchvision|torchaudio"
grep -vEi "^(${EXCLUDE_PKGS})([<>=!~;[:space:]]|$)" requirements.txt \
  > requirements.tmp && mv requirements.tmp requirements.txt
pip install -r requirements.txt

# Explicitly install packages mentioned in README install instructions
pip install opencv-python "huggingface_hub==0.35.0"

# ── Block H: Smoke test ───────────────────────────────────────────────────────
python -c "import torch; print('torch', torch.__version__, '| cuda:', torch.cuda.is_available())"
python -c "import cv2; import huggingface_hub; print('mvinverse deps OK')"
