#!/usr/bin/env bash
# ReCamMaster — https://github.com/KlingAIResearch/ReCamMaster
# Prerequisite: /workspace = cloned repo root (bind-mounted by docker_agent)
# Generated by: rocm-install-script-generator skill v1.1.0
# Note: DiffSynth-Studio (used internally) requires Rust+Cargo to compile extensions.
set -e
cd /workspace

# ── Block A: Rust/Cargo (required by DiffSynth-Studio) ───────────────────────
if ! command -v cargo &>/dev/null; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  source "$HOME/.cargo/env"
fi

# ── Block B: Conda env ────────────────────────────────────────────────────────
conda create -n recammaster python=3.11 -y
source /opt/conda/etc/profile.d/conda.sh && conda activate recammaster

# Ensure cargo is on PATH inside conda env
source "$HOME/.cargo/env"

# ── Block C: ROCm PyTorch ─────────────────────────────────────────────────────
pip uninstall -y torch torchvision torchaudio
pip install --pre torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 \
  --index-url https://download.pytorch.org/whl/rocm6.4

# ── Block F: pip install -e . (setup.py at root) ──────────────────────────────
# This installs DiffSynth-Studio and builds Rust extensions
pip install -e . --no-build-isolation

# ── Block E: requirements.txt (if present, for any extras) ───────────────────
if [ -f requirements.txt ]; then
  EXCLUDE_PKGS="torch|torchvision|torchaudio"
  grep -vEi "^(${EXCLUDE_PKGS})([<>=!~;[:space:]]|$)" requirements.txt \
    > requirements.tmp && mv requirements.tmp requirements.tmp2
  pip install -r requirements.tmp2
  rm -f requirements.tmp2
fi

# Training extras (optional, skip if not needed)
# pip install lightning pandas websockets

# ── Block H: Smoke test ───────────────────────────────────────────────────────
python -c "import torch; print('torch', torch.__version__, '| cuda:', torch.cuda.is_available())"
python -c "import diffsynth; print('diffsynth OK')" || \
  echo "[WARN] diffsynth not importable — check Rust build output above"
